// ===========================================
// Wall of Fame: every RSAK black belt, in the order they earned it.
// To update: replace the placeholder names below, one per line, in quotes,
// with a comma after each name except the last.
// The black belt counter updates itself from this list.
// ===========================================

const BLACK_BELTS = [
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]",
  "[John Doe]",
  "[Jane Doe]"
];

// Build the wall
const wall = document.getElementById("wall");
const total = document.getElementById("bb-total");

if (total) total.dataset.target = BLACK_BELTS.length;

if (wall) {
  BLACK_BELTS.forEach((name, i) => {
    const li = document.createElement("li");
    li.innerHTML = '<span class="wall-num"></span><span class="wall-name"></span>';
    li.querySelector(".wall-num").textContent = i + 1;
    li.querySelector(".wall-name").textContent = name;
    wall.appendChild(li);
  });

  // Search by name
  const search = document.getElementById("wall-search");
  const empty = document.getElementById("wall-empty");
  if (search) {
    search.addEventListener("input", () => {
      const q = search.value.trim().toLowerCase();
      let shown = 0;
      wall.querySelectorAll("li").forEach((li) => {
        const match = li.textContent.toLowerCase().includes(q);
        li.classList.toggle("is-hidden", !match);
        if (match) shown++;
      });
      if (empty) empty.hidden = shown > 0;
    });
  }
}
